# Basic
name:               "Hassaan Ahmed"
title:              "Hassaan Ahmed"
description:        "a creative based in the san francisco bay area"
author:             Hassaan Ahmed
logo:               /assets/images/logo.png

# URL
url:                "//hassaanahmed.com"
baseurl:            ""
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "Linkedin"
    href:           "//linkedin.com/in/hassaan-ahmed-ca"
  - name:           "Github"
    href:           "//github.com/hahmed427"
  - name:           "Email"
    href:           "mailto:me@hassaanahmed.com"
  - name:           "RSS"
    href:            "/feed.xml"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Twitter
twitter:
    card:           summary

# Plugins
plugins:
    - jekyll-seo-tag
