# Basic
name:               "Hassaan Ahmed"
title:              "Hassaan Ahmed"
description:        "a computer science student at the university of michigan"
author:             Hassaan Ahmed
logo:               /assets/images/logo.png

# URL
url:                "//ahmedxyz.github.io"
baseurl:            ""
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Google Analytics
google_analytics:   UA-124728562-1

# Navigation
nav:
  - name:           "Linkedin"
    href:           "//linkedin.com/in/ahmedxyz"
  - name:           "Github"
    href:           "//github.com/ahmedxyz"
  - name:           "Email"
    href:           "mailto:ahmedxyz@umich.edu"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Twitter
twitter:
    card:           summary

# Plugins
plugins:
    - jekyll-seo-tag
